### ISSUE TITLE
Cluster contains no pools to draw from for key

### ISSUE THREAD

**Issue by regbo** [bbottema/clustered-object-pool#3]
Maybe I am missing somethign here, but in the docs it says

_When creating clusters, you can optionally preregister pools with specific behavior. If you don't pools and clusters and pools are created on the fly with the provided defaults_.

However, if I use this simple example:

````java
		ClusterConfig<String, Date> clusterConfig = ClusterConfig.<String, Date>builder()
				.allocatorFactory(pk -> new Allocator<Date>() {

					@Override
					public Date allocate() {
						return new Date();
					}
				})
				.defaultCorePoolSize(1)
				.defaultMaxPoolSize(Integer.MAX_VALUE)
				.build();

		ResourceClusters<UUID, String, Date> clusters = new ResourceClusters<>(clusterConfig);
		UUID keyCluster1 = UUID.randomUUID();

		// claim from cluster, blocking until a resource becomes available
		var resource = clusters.claimResourceFromCluster(keyCluster1);
		try {
			System.out.println(resource.getAllocatedObject());
		} finally {
			resource.release();
		}
````

I get the following:

````java
Exception in thread "main" java.lang.IllegalStateException: Cluster contains no pools to draw from for key 'ResourcePools(clusterCollection=[], poolsShuttingDown=[])'
	at org.bbottema.clusteredobjectpool.core.ResourceClusters.cycleToNextPool(ResourceClusters.java:184)
	at org.bbottema.clusteredobjectpool.core.ResourceClusters.claimResourceFromCluster(ResourceClusters.java:124)
	at test.PoolTest.main(PoolTest.java:30)
````

Shouldn't pools be created on demand?

**Comment by regbo** [comment]
Nevermind, it looks like you need a pool key as that is undefined. I think the docs should be updated to specify that, as the example is a little confusing.
